[package]
name = "rakme"
version = "0.1.0"
edition = "2024"

[dependencies]
ab_glyph = "0.2.32"
arboard = { version = "3.6.1", default-features = false }
pixels = "0.17.2"
ropey = { version = "1.6.1", default-features = false, features = ["simd"] }
tiny-skia = "0.12.0"
tree-sitter = "0.27.0"
# TODO: get rid of the below line when you figure out how to load user installed grammars
tree-sitter-rust = "0.24.2"
winit = "0.30.13"
